---
output: pdf_document
---
\justifying
\setlength\parskip{5ex}
\noindent
Hoy en día palabras como machine learning o inteligencia artificial, o conceptos relacionados con aplicaciones de los mismos, nos suenan relativamente familiares porque forman parte indiscutible del mundo actual. Aunque no lo parezca, y no sea de conocimiento general, este tipo de aplicaciones que intentan trasladar el pensamiento o razonamiento humano a un lenguaje que los ordenadores sean capaces de entender y reproducir fueron creadas de manera teórica en la segunda mitad del siglo XX, así que en realidad tienen ya sus décadas de vida. Lo sorprendente es que vienen teniendo un auge muy grande en la última decada. Esto se debe a que las limitaciones prácticas que tenían estos modelos en el momento de ser creados se han podido superar en los últimos tiempos. Éstas limitaciones prácticas a las que se hace referencia son básicamente la enorme capacidad computacional requerida para poner en práctica todos estos algoritmos de IA. Ésto es lógico ya que, si en realidad se intenta trasladar el razonamiento humano a un orderador, éste tiene que ser capaz de procesas grandes cantidades de información y realizar operaciones a una alta velocidad. En la época de su creación las máquinas tenían una capacidad computacional muy inferior a la actual, ya que el crecimiento que esta capacidad ha tenido en las últimas décadas ha sido exponencial. La potencia computacional existente hoy en día ha permitido el desarrollo de modelos que previamente no se podían desarrollar a causa de las restricciones físicas en la maquinaria. Además, este aumento de capacidad computacional viene asociado con una reducción de los costes de las máquinas, cosa que potencia la aparición de nuevos elementos de IA. El objetivo del presente trabajo es el de analizar las el contexto actual de la IA en el mundo de las finanzas, empezando con la evolución histórica que viene teniendo la implantación de la IA en el sector financiero hasta la actual situación y aplicaciones. En ese sentido se analiza la situación actual para poder analizar cuáles han sido las consecuencias de la implantación de la inteligencia artificial en los mercados financieros. La motivación presente detrás de este trabajo está clara: en un mundo donde los conceptos relacionados con la IA artificial están de moda, personalmente creía necesaria la elaboración de un estudio riguroso que detallara las aplicaciones actuales y las consecuencias de las mismas.

\justifying
\noindent
En esta línea una de las tareas dentro del sector de las finanzas que más se ha intentado desarrollar es la de intentar predecir el precio de un stock, que ha sido una materia objeto de estudio desde los últimos años. Los *brokers* llevan años intentando implementar y mejorar la manera en la que se predicen los precios futuros de los stocks. Este esfuerzo se debe a la potencial utilidad de un modelo preciso en cuanto a la predicción del precio ya que éste sería indispensable para enriquirse haciendo *trading*. Debido a la complejidad de las series temporales de los precios una nueva rama de investigación se está desarrollando rápidamente. Ésta rama de investigación concentra los esfuerzos en intentar predecir la *dirección* del stock en cuestión en vez de intentar predecir el precio exacto. Estos modelos de predicción de la dirección del movimiento de los stocks, llamados SMD por sus siglas en inglés (Stock Movement Direction), consiguen alcanzar un rendimiento predictivo suficiente como para utilizarlos como complemento al análisi fundamental a la hora de tomar una decisión de inversión. Sin embargo, gracias a la aparición de nuevos modelos de ML tales como las redes neuronales recurrentes, la predicción del precio de cierre en está empezando a parecer plausible, y los modelos que se construyen en esta línea, capaces de ser útiles ayudando en un proceso de toma de decisiones de inversión.

\justifying
\noindent
En el trabajo que se desarrolla a continuación se proponen distintas aplicaciones utilizando modelos de IA y machine learning en un sub-sector concreto del sector de las finanzas como es el de los mercados inversiones en activos. De una manera general se pretende mostrar como el abanico de posibilidades en este campo, en cuanto a los distintos tipos de aplicaciones que se pueden realizar, es muy amplio. De una manera más concreta las aplicaciones que se desarrollan a continuación se pueden clasificar en dos grandes grupos. La característica que los distingue es el objetivo final que tiene cada uno de ellos. De una manera técnica se podría decir que los dos grupos de experimentos se distinguen al ser la variable aleatoria que se pretende modelizar de una naturaleza distinta. El primero consiste en el desarrollo de un tipo de modelos concretos, los llamados SMD o modelos de predicción de la dirección de movimiento del precio de un *stock* utilizando un conjunto de indicadores técnicos como variables predictoras. Usando este tipo de modelos se elaboran distintos experimentos los cuales se agrupan en 3 sub-tipos. Se realiza un primer acercamiento detallado utilizando 4 empresas como ejemplo y con un tipo de modelos llamados Random Forest. Posteriormente se aplica el mismo marco conceptual sobre un conjunto más elevado de empresas utilizando computación en paralelo sobre arquitectura distribuida para aumentar la capacidad de cálculo. Finalmente se propone un ejemplo de aplicación de estos modelos conceptuales construyendo otro tipo de modelos de *machine learning*, distintos al Random Forest, utilizando un algoritmo automático de construcción de modelos, concepto conocido en inglés como *automatic machine learning*. El segundo gran grupo de experimentos explora la posibilidad de predecir dos de los más importantes valores a tener en cuenta en un mercado de inversión como son, por un lado, el precio de cierre diario de una determinada acción y, por otro, la rentabilidad diaria asociada a esa misma acción. Este proceso de predicción se elabora utilizando un tipo de modelo concreto de *deep learning* llamado Long-Short Term Memory Recurrent Neural Network. Este tipo de modelos permite conservar dependencias temporales lejanas en el tiempo por lo que se considera un modelo potencialmente útil a la hora de predecir tanto el precio de cierre como la rentabilidad diaria de una acción en un mercado de inversión.

\justifying
\noindent
Cabe destacar que todo el conjunto de experimentos que se desarrollan en esta tesis, incluyendo el considerar dos tipos de predicciones conceptuales (dirección y valor), está en línea con la idea de poder utilizar todo este tipo de herramientas a la hora de considerar una decisión de inversión real. Es decir, todos los experimentos se elaboran teniendo en mente que el objetivo de su elaboración es formar parte, por si mismos o al combinarse con otras herramientas, de una plataforma que permita obtener la información necesaria para poder tomar una decisión de inversión fundamentada. El poder predecir tanto la dirección como el valor mismo que el precio de una acción puede tener dentro de un mercado de inversión de una manera precisa sería sin duda una ayuda fundamental para cualquier persona, profesional o no, que quisiera plantearse una decisión de inversión en un mercado de acciones.

