---
output: pdf_document
---

\noindent
En primer lugar se analizan los posibles efectos de la inteligencia artificial en los mercados financieros. Una de los conocimientos globales que se tiene actualmente es el hecho de que la IA y el machine learning tienen el potencial para mejorar substancialmente la eficiencia en el procesamiento de información. Eso deriva intevitablemente en una reducción de las asimetrías en la información que tienen los agentes económicos y por lo tanto puede reforzar la función de información del sistema financiero. Los mecanismos por los cuales este refuerzo podría ocurrir incluyen los siguientes factores. Por un lado, estos sistemas de IA puede permitir que ciertos agentes en el mercado recojan y analicen datos a mayor escala. Con este análisis los participantes del mercado son potencialmente capaces de entender (mejor) la relación entre distintos factores y la formulación de los precios de mercado. Ejemplos de los distintos factores que se pueden relacionar con el proceso de definición de los precios de mercado son los sentimientos o estádos de ánimo extraídos de las redes sociales o las notícias gracias a técnicas de *sentiment analysis*. Esto podría reducir las asimetrías en la información y de esta manera contribuir a la eficiencia y estabilidad de los mercados (véase [@IOSCO] p. 28). Por otro lado los modelos de machine learning e IA pueden beneficiar a los participantes en un mercado al reducir los costes asociados a su participación. Además la IA pude permitir a los agentes ajustar sus estrategias de inversión de una manera casi inmediata (o en tiempo real), como respuesta a una realidad cambiante. De esta manera se reducen en general los costes de las transacciones en el sistema a la par que se mejora el descubrimiento de los precios [@AIboard]. Paralelamente se observan otras posibilidades. Si los participantes en los mercados terminan pot utilizar técnicas similares de machine learning los riesgos correlacionados podrían derivar en riesgos de estabilidad de los mercados. Es decir, si el uso de *traders* basados en modelos de aprendizaje automático se empieza a ser mejor, de una manera masiva, que el *trading* clásico, esto puede provocar que muchos agentes en el futuro decidan también utilizar este tipo de técnicas y esdevengan, en definitiva, un sistema que puede amplificar los *shocks* financieros, tanto positivos como negativos.

\noindent
En segundo lugar se analizar los posibles efectos de la IA en las instituciones financieras. Por un lado los sistemas de machine learning pueden mejorar los ingresos y reducir los costes para las mismas, ya que pueden mejorar el procesamiento de distintas operaciones que este tipo de insituciones utilizan. Al tener éstos un gran componente computacional, el hecho de incorporar el machine learning para automatizar y mejorar procesos de negocio rutinarios puede trasladarse en unos costes operacionales más bajos y, en general, hacen que estas empresas sean más rentables. Por otro lado, y como ya se ha analizado en la presente tesis, la IA y el machine learning se pueden utilizar y se utilizan para la gestión del riesgo. Por ejemplo, técnicas y modelos de gestión de riesgos de cola (distribuciones de riesgos con las colas pesadas no normales). Además también se pueden utilizar para detectar el fraude bancario o financiero, las transacciones sospechosas y estimando el riesgo de ciber ataques mejorando, en definitiva, el proceso de gestión del riesgo. Sin embargo todas estas herramientas tienen un peligro potencial ya que pueden pasar por alto nuevas fuentes de riesgo al no estar presentes en los datos históricos utilizados para entrenar los modelos. Otro de los posibles efectos sobre las instituciones financieras se analiza seguidamente. El hecho de que el desarrollo en el campo de la inteligencia artificial sea de carácter *open source* y con un uso intensivo de datos puede animar a las instituciones financieras a colaborar con otras e incluso con otros sectores como el comercio on-line y las economías colaborativas. En este sentido fomenta incrementar y potencial la colaboración inter-sectorial. 

\noindent
En general, en el caso de las instituciones financieras reguladoras, la aplicación de la IA puede beneficiar al sector en general ayudando a mejorar los sistemas actuales de control, gestión y regulación. No obstante todos estos efectos positivos vienen con unos riesgos potenciales asociados. La creación de modelos de toma de decisiones automáticas, que normalmente se convierten en cajas negras, puede hacer dificil para las instituciones financieras el captar cómo se formulan las decisiones, especialmente en casos de inversión y *trading* (véase [@black] para una descripción concisa de los problemas de las *black boxes* en la IA y la toma de decisiones). Esto puede derivar en un serio problema cuando estos algoritmos causan situaciones de *Flash Crush* o cuando están relacionados con eventos extremos. Esto sin duda significa una falta de transparencia en torno a los sistemas de IA que puede ser problemático para las instituciones a la hora de entender cómo y por qué han ocurrido los eventos exremos o no deseados derivados de la aplicación de los mismos.

\noindent
Otro de los potenciales riesgos de la IA es la falta de transparencia en cuanto a las responsabilidades derivadas de las posibles pérdidas económicas en los intermediaros que estos modelos puedan causar. Por ejemplo en el caso de que una aplicación de IA desarrollada por un tercero provoque grandes pérdidas. En este caso, es la institución que provoca las gestión o movimiento la única responsable de las pérdidas? O serán las instituciones capaces de gestionar las potenciales demandas en contra de los desarrolladores de la aplicación? En este sentido el debate está abiero, y habrá que seguir en el futuro las noticias relacionadas con este tema. En este sentido, es posible que la aplicación transversal de la IA en el sector financiero provoque cambios en la manera en la que se regula este sector. Por último, cabe destacar las grandes dependencias sobre terceros agentes que la aplicación de la IA en finanzas tiene. El desarrollo de estas aplicaciones se sostiene en general gracias a un gran número de empresas tecnológicamente avanzadas que son las proveedoras de estos servicios. Si las grandes instituciones financieras confían tanto en los terceros agentes, se pueden generar grandes disrupciones en el sistema si estos terceros agentes experimentan situaciones de alto riesgo o quiebras. Especialmente en el futuro habrá que tener presente estos riesgos a la hora de desarrollar herramientas de IA encargadas de misiones o tareas consideradas críticas [@AIboard].

\noindent
En tercer lugar se analizan los potenciales efectos de la IA en los consumidores e inversores. En general, ya se ha visto que la IA y el machine learning tienen el potencial de reducir costes y de aumentar la eficiencia de los servicios financieros y, por tanto, los consumidores pueden verse beneficiados de distintas maneras. Uno de los beneficios directos de la reducción de costes es que ésta puede verse trasladada a los consumidores en forma de menores tasas y costes de transacción. Además los consumidores e inversores pueden tener acceso a una mayor variedad de servicios financieros. A su vez también pueden facilitar unos servicios financieros mucho más customizados y personalizados ya que la IA aplicada al big data (*big data science*) permite a las compañías analizar las características de los clientes y, así, poder ofrecer servicios ajustados a diferentes perfiles de cliente. Sin embargo, la utilización de estos datos de los consumidores puede llevar a problemas de privacidad de datos y  seguridad de la información (véase [@privacy] para más información acerca de los problemas relacionados con la privacidad de los datos y IA). Gracias al uso intensivo de este tipo de datos privados los modelos de machine learning pueden llegar a ser discriminatorios por razones de raza, sexo, religión, etc. Evitar este tipo de modelos discriminatorios en ambientes como la evaluación del riesgo de crédito, modelos de acceso a crédito o calculadores de cuotas de servicios de seguros.