---
output: pdf_document
---

<!-- \setlength\parskip{5ex} -->
<!-- \justifying -->
El término inteligencia artificial es hoy en día un concepto con el que mucha gente ya está familiarizada. En realidad, empieza a estar presente en todas las facetas del mundo. Ya sea de una manera consciente o no, la sociedad del siglo XXI está ya intrínsecamente ligada a los procesos informaticos y a los sistemas automatizados de inteligencia artificial. Se pueden encontrar numerosas aplicaciones en el mundo real de sistemas de inteligencia artificial y machine learning en campos como la medicina, los deportes, la economía o los negocios. La implantación de estos sistemas y, en especial, su auge, se debe al gran crecimiento en cuanto a la disponibilidad de datos que ha experimentado nuestra sociedad de la información. Este tipo de aplicaciones de IA aprovechan este gran volúmen de datos para extraer toda la información posible de ellos y, de esta manera, ayudar a elaborar tareas que requieren de una cierta inteligencia humana pero que se han conseguido trasladar a los sistemas informáticos. Desde el proceso de obtención de datos personales que hacen las compañías detrás de las redes sociales, hasta los sistemas de perfilado que tienen los bancos o las compañías de seguros, los sistemas de IA afectan a la vida de cada ser humano en la sociedad globalizada en la que vivimos actualmente, seamos conscientes de ello o no.

\setlength\parskip{5ex}
En el presente trabajo se pretende elaborar un estudio sobre un sector concreto como lo es el sector financiero. Este sector es uno de los pilares fundamentales de los sistemas económicos actuales y juegan un papel clave en todas las esferas sociales, desde las grandes compañías hasta los principales agentes de consumo, las familias. A causa del papel fundamental e indispensable en la sociedad del siglo XXI de este sector, en el presente trabajo se pretende analizar el impacto que tienen las aplicaciones actuales de inteligencia artificial y sistemas basados en técnicas de machine learning en el sector financiero. En primer lugar se analiza la evolución de la IA desde una perspectiva histórica para posteriormente detallar ejemplos de aplicaciones actuales de IA en el sector financiero. Con el contexto actual en mente se pretende indagar en las consecuencias directas (y que ya están teniendo lugar) de estas aplicaciones, así como analizar desde un prisma económico los potenciales efectos que puede tener la aplicación de la IA en el mundo de las finanzas de continuar su implantación con los ritmos actuales. Anticipando un crecimiento casi exponencial, se proponen distintos problemas que pueden aparecer en un futuro desde perspectivas micro y macro económicas. Posteriormente se desarrollan distintas aplicaciones de machine learning relacionadas con el sector financiero, en especial con la inversión en mercados de activos. Se construye un modelo conceptual de predicción de la dirección de movimiento del precio de cierre de un stock y se analizan distintos tipos de modelos/herramientas de ML con los que construirlo. También se elabora otro tipo de aplicación con redes reuronales recurrentes o profundas (tipo LSTM) sobre los precios de cierre de los activos financieros. Con el objetivo de comparar las distintas herramientas con las que se construyen los modelos de predicción de la dirección de movimiento, se analizan los resultados y se desarrollan las conclusiones a las que se llega, tanto respecto al futuro del desarrollo de la IA en el sector financiero como respecto a los modelos creados.