
target_calc<-function(data,freq){
  target<-c()
  for(i in 1:(nrow(data)-freq)){
    if(as.numeric(data[i+freq,4])>as.numeric(data[i,4])){
      target[i]<-"Up"
    }else{
      target[i]<-"Down"
    }
  }
  return(target)
}





feature_extraction_finance<-function(data){
  data<-data %>%

  #Aroon
  cbind(aroon(data[,c("High","Low")],20)) %>%

  #----------------------------------------

#Simple moving average 10 day
cbind(sma10=SMA(data[,"Close"],10)) %>%

  #----------------------------------------

#exponential moving average 10 day
#cbind(ema10=EMA(data[,"Close"],10)) %>%

  #----------------------------------------

#momentum 1 day
cbind(mom1=momentum(data[,"Close"],1)) %>%
  cbind(mom2=momentum(data[,"Close"],2)) %>%
  cbind(mom3=momentum(data[,"Close"],3)) %>%
  cbind(mom4=momentum(data[,"Close"],4)) %>%
  cbind(mom5=momentum(data[,"Close"],5)) %>%

  #momentum 9 day
  cbind(mom9=momentum(data[,"Close"],9)) %>%

  cbind(mom15=momentum(data[,"Close"],15)) %>%

  #----------------------------------------

#Rate of change 1 day
cbind(ROC1=ROC(data[,"Close"],1)) %>%

  #Rate of change 9 day
  cbind(ROC9=ROC(data[,"Close"],9)) %>%

  #----------------------------------------

#fastK%, fastD% and slowD%
#nFastK = 14, nFastD = 3, nSlowD = 3
cbind(data.frame(stoch(as.xts(data[,c("High","Low","Close")])))) %>%

  #SMI
  #n = 13, nFast = 2, nSlow = 25
  cbind(SMI=data.frame(SMI(as.xts(data[,c("High","Low","Close")])))[,1]) %>%

  #----------------------------------------

#RSI
cbind(RSI=RSI(data[,"Close"])) %>%

  #----------------------------------------

#Williams Accumulation/Distribution
cbind(data.frame(wAD=williamsAD(as.xts(data[,c("High","Low","Close")])))) %>%

    
  #Williams Percentage range
  cbind(data.frame(WPR(as.xts(data[,c("High","Low","Close")]))))

#names(data)[23]<-"WPR"
names(data)[4]<-"Close_"
names(data)[which(names(data)=="Close")]<-"WPR"
names(data)[4]<-"Close"
#----------------------------------------

data<-data %>%
  #Moving Average convergence divergence
  cbind(macd=MACD(data[,"Close"],12, 26, 9, maType="EMA" )[,1]) %>%

  #----------------------------------------

#Comodity Channel Index
cbind(data.frame(CCI=CCI(as.xts(data[,c("High","Low","Close")])))) %>%

  #----------------------------------------

#On Balance Volume
cbind(OBV=OBV(data[,"Close"],data[,"Volume"])) %>%

  #----------------------------------------

#Average true range, true range1 and true range2
cbind(data.frame(ATR(as.xts(data[,c("High","Low","Close")]))))

b3<-data.frame(tr2=((data[,4]-data$trueLow)/(data$trueHigh-data$trueLow)))

data<-data %>%
  cbind(b3) %>%

  select(-c(trueHigh,trueLow)) %>%

  #----------------------------------------

#Trend detection index, using both TDI and DI
cbind(TDI(data[,"Close"])) %>%

  #ADX and DX and DIp/DIn
  cbind(data.frame(ADX(as.xts(data[,c("High","Low","Close")]),20)))

b2<-data.frame(PNratio=data$DIp/data$DIn)

data<-data %>%
  cbind(b2) %>%

  select(-c(DIp,DIn)) %>%

  #Bollinger band width
  cbind(data.frame(BBands(as.xts(data[,c("High","Low","Close")]))))

b<-data.frame(BBwidth=((data$up-data$dn)/data$mavg))

data<-data %>%
  cbind(b) %>%

  select(-c(dn,up,mavg)) %>%

  #------------------------------------
select(-c(oscillator))

data<-data[-c(1:39),] #deleting NA generated by average calculations

data<-data[,-c(1:5)] #borramos variables que no se utilizan

return(data)
}
